# Generated by Django 5.2.12 on 2026-03-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duvida',
            options={'ordering': ['-data_pergunta'], 'verbose_name': 'Dúvida'},
        ),
        migrations.RenameField(
            model_name='duvida',
            old_name='criada_em',
            new_name='data_pergunta',
        ),
        migrations.RenameField(
            model_name='duvida',
            old_name='pergunta',
            new_name='texto_pergunta',
        ),
        migrations.RenameField(
            model_name='duvida',
            old_name='resposta',
            new_name='texto_resposta',
        ),
        migrations.RemoveField(
            model_name='duvida',
            name='respondida',
        ),
        migrations.RemoveField(
            model_name='duvida',
            name='usuario',
        ),
        migrations.AddField(
            model_name='duvida',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duvida',
            name='respondido_por',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFISSIONAL_SUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duvida',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESPONDIDA', 'Respondida')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='duvida',
            name='usuario_idoso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_duvidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
