# Generated by Django 5.2.12 on 2026-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IDOSO', 'Idoso'), ('PROFISSIONAL_SUS', 'Profissional SUS'), ('ADMIN', 'Administrador')], default='IDOSO', max_length=20),
        ),
    ]
