services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appsifilis_db
      - POSTGRES_USER=kelvin
      - POSTGRES_PASSWORD=senha_forte

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://kelvin:senha_forte@db:5432/appsifilis_db
    depends_on:
      - db

volumes:
  postgres_data: