# Generated by Django 5.2.12 on 2026-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('OQUE', 'O que é?'), ('PREV', 'Prevenção'), ('TRAT', 'Tratamento')], max_length=4)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('referencia', models.CharField(default='MARTINS et al, 2024', max_length=255)),
            ],
        ),
    ]
