# Generated by Django 5.2.12 on 2026-03-21 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('CACA', 'Caça-Palavras'), ('AGIL', 'Agilidade (Baratinha)')], max_length=4)),
                ('pontos', models.IntegerField(default=0)),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pontuações',
                'ordering': ['-pontos'],
            },
        ),
    ]
